INSERT INTO Quiz.QUESTION_ANSWER (questionID, answerID) VALUES (1, 1);
INSERT INTO Quiz.QUESTION_ANSWER (questionID, answerID) VALUES (2, 2);
INSERT INTO Quiz.QUESTION_ANSWER (questionID, answerID) VALUES (3, 3);
INSERT INTO Quiz.QUESTION_ANSWER (questionID, answerID) VALUES (4, 4);
INSERT INTO Quiz.QUESTION_ANSWER (questionID, answerID) VALUES (5, 5);