INSERT INTO Quiz.QUIZ_QUESTION (questionID, quizID) VALUES (1, 1);
INSERT INTO Quiz.QUIZ_QUESTION (questionID, quizID) VALUES (2, 1);
INSERT INTO Quiz.QUIZ_QUESTION (questionID, quizID) VALUES (3, 1);
INSERT INTO Quiz.QUIZ_QUESTION (questionID, quizID) VALUES (4, 1);
INSERT INTO Quiz.QUIZ_QUESTION (questionID, quizID) VALUES (5, 1);